"""
main.py

FastAPI server for the immigration RAG assistant.
Exposes a single /api/chat endpoint that the frontend calls.

Why FastAPI over Flask?
- Native async support (important for concurrent requests)
- Automatic request/response validation via Pydantic
- Auto-generated API docs at /docs (useful for frontend dev)
- Type hints throughout — cleaner, more maintainable code

Usage:
    uvicorn backend.main:app --reload --port 8000
"""

import logging
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field
from contextlib import asynccontextmanager

from backend.config import validate_config
from backend.chain import run_chain
from backend.memory import clear_memory, get_active_sessions

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s"
)
log = logging.getLogger(__name__)


# ── Lifespan (startup + shutdown) ─────────────────────────────────────────────

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Runs on server startup and shutdown.

    Why validate config at startup?
    Fail fast — if QDRANT_URL is missing we want to know immediately
    when the server starts, not when the first user request comes in
    and gets a cryptic error.
    """
    # Startup
    log.info("Starting ImmigrationIQ backend...")
    validate_config()
    log.info("Config validated. All environment variables present.")
    log.info("Server ready.")

    yield  # server runs here

    # Shutdown
    log.info("Shutting down. Active sessions: %d", get_active_sessions())


# ── App initialization ────────────────────────────────────────────────────────

app = FastAPI(
    title="ImmigrationIQ API",
    description="RAG-powered US immigration and tax guidance assistant",
    version="1.0.0",
    lifespan=lifespan,
)

# ── CORS middleware ───────────────────────────────────────────────────────────
# CORS (Cross-Origin Resource Sharing) allows the Next.js frontend
# running on localhost:3000 to call this API on localhost:8000.
# Without this, the browser blocks the request as a security measure.
# In production you'd replace "*" with your actual frontend domain.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:3001"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Request / Response models ─────────────────────────────────────────────────

class ChatRequest(BaseModel):
    """
    Incoming chat request from the frontend.
    Pydantic validates types and required fields automatically.
    """
    session_id: str = Field(
        ...,
        description="UUID generated by frontend on page load",
        min_length=1,
    )
    message: str = Field(
        ...,
        description="The user's question",
        min_length=1,
        max_length=2000,
    )
    mode: str = Field(
        default="student",
        description="Response mode: 'student' or 'professional'",
        pattern="^(student|professional)$",
    )


class SourceItem(BaseModel):
    """A single source citation."""
    url:          str
    section:      str
    doc_type:     str
    jurisdiction: str


class ChatResponse(BaseModel):
    """
    Response sent back to the frontend.
    Structured so the frontend can render answer + citations separately.
    """
    answer:      str
    sources:     list[SourceItem]
    complexity:  str   # "simple" or "complex" — useful for frontend analytics
    tokens_used: int


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health")
async def health_check():
    """
    Simple health check endpoint.
    Used by deployment platforms to verify the server is running.
    Also useful during development to confirm the server started correctly.
    """
    return {
        "status": "healthy",
        "active_sessions": get_active_sessions(),
    }


@app.post("/api/chat", response_model=ChatResponse)
async def chat(request: ChatRequest):
    """
    Main chat endpoint.

    Receives a user message + session context,
    runs the full RAG chain, returns the answer with citations.

    The frontend sends:
        POST /api/chat
        {
            "session_id": "uuid-from-frontend",
            "message": "What is the H1B filing fee?",
            "mode": "student"
        }

    The backend returns:
        {
            "answer": "The H1B filing fee is...",
            "sources": [...],
            "complexity": "simple",
            "tokens_used": 1243
        }
    """
    try:
        result = run_chain(
            message=request.message,
            session_id=request.session_id,
            mode=request.mode,
        )
        return ChatResponse(
            answer=result["answer"],
            sources=[SourceItem(**s) for s in result["sources"]],
            complexity=result["complexity"],
            tokens_used=result["tokens_used"],
        )
    except Exception as e:
        log.error(f"Chain error for session {request.session_id[:8]}: {e}")
        raise HTTPException(
            status_code=500,
            detail="An error occurred processing your request. Please try again."
        )


@app.delete("/api/session/{session_id}")
async def clear_session(session_id: str):
    """
    Clear conversation memory for a session.
    Called when the user clicks "New Chat" on the frontend.
    """
    clear_memory(session_id)
    return {"status": "cleared", "session_id": session_id}


@app.get("/api/health/detailed")
async def detailed_health():
    """
    Detailed health check — verifies all downstream services.
    Useful for debugging connectivity issues in production.
    """
    from qdrant_client import QdrantClient
    from backend.config import QDRANT_URL, QDRANT_API_KEY, QDRANT_COLLECTION_NAME

    status = {
        "server": "healthy",
        "active_sessions": get_active_sessions(),
        "qdrant": "unknown",
    }

    try:
        client = QdrantClient(url=QDRANT_URL, api_key=QDRANT_API_KEY)
        info   = client.get_collection(QDRANT_COLLECTION_NAME)
        status["qdrant"] = f"healthy ({info.points_count} points)"
    except Exception as e:
        status["qdrant"] = f"error: {str(e)}"

    return status