"""
memory.py

Session-scoped conversational memory for the RAG chain.

Each chat session gets its own ConversationBufferWindowMemory instance.
Sessions are identified by a UUID generated on the frontend when the
chat window opens. No persistence — memory lives in RAM and is lost
when the server restarts or the session ends.

Why in-memory and not a database?
- No user accounts or login — nothing to persist across sessions
- Simpler architecture — no Redis or Postgres dependency
- Privacy by design — conversations are never stored permanently
- Fresh start per session is the intended UX
"""

import logging
from langchain.memory import ConversationBufferWindowMemory
from backend.config import MEMORY_K

log = logging.getLogger(__name__)

# ── Session store ─────────────────────────────────────────────────────────────
# Simple dict mapping session_id (UUID string) → memory instance
# In production with high traffic you'd use Redis for this
# For our use case an in-memory dict is correct and sufficient
_session_store: dict[str, ConversationBufferWindowMemory] = {}


def get_memory(session_id: str) -> ConversationBufferWindowMemory:
    """
    Get or create a memory instance for a session.

    If this session_id hasn't been seen before, creates a fresh memory.
    If it has, returns the existing memory with conversation history intact.

    Args:
        session_id: UUID string generated by the frontend on page load.
                    Same session_id across multiple messages = same conversation.
                    New session_id = fresh conversation, no history.

    Returns:
        ConversationBufferWindowMemory instance for this session.
    """
    if session_id not in _session_store:
        log.info(f"Creating new memory for session: {session_id[:8]}...")
        _session_store[session_id] = ConversationBufferWindowMemory(
            k=MEMORY_K,                  # keep last k conversation turns
            memory_key="chat_history",   # key used in the prompt template
            return_messages=True,        # return as message objects not string
            output_key="answer"          # which chain output to store
        )
    return _session_store[session_id]


def clear_memory(session_id: str) -> None:
    """
    Clear memory for a specific session.
    Called when user clicks "New Chat" on the frontend.
    """
    if session_id in _session_store:
        del _session_store[session_id]
        log.info(f"Cleared memory for session: {session_id[:8]}...")


def get_active_sessions() -> int:
    """
    Return count of active sessions in memory.
    Useful for monitoring — log this periodically in production.
    """
    return len(_session_store)


def clear_all_sessions() -> None:
    """
    Clear all sessions — called on server shutdown or for testing.
    """
    _session_store.clear()
    log.info("All session memory cleared.")